### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by nigamanthsrivatsan**
You had a double quote in one of the files and I was correcting your grammar and making the README better.

### CODE REVIEW

**Comment by nigamanthsrivatsan** [comment]
@superzackx?

**Comment by superzackx** [comment]
I'm not working on this project anymore.

**Comment by nigamanthsrivatsan** [comment]
You can still merge though.

**Comment by superzackx** [comment]
I'm not really working on this project anymore...

**Pull request closed without merging**
